version: '3'

tasks:
  compile-lib-linux:
    g++ -std=c++17 -fPIC -shared -o libs/libextract_linux_amd64.a extern/wrapper.cpp

  compile-lib-windows:
    g++ -std=c++17 -fPIC -shared -Iinclude -o libs/libextract_windows_amd64.a extern/wrapper.cpp